services:
  postgres:
    image: "postgres:18.1"
    environment:
      - 'POSTGRES_DB=socratic-tutor'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    volumes:
      - db_postgres:/var/lib/postgresql
    ports:
      - '${POSTGRES_PORT:-4321}:5432'

  chroma:
    image: 'chromadb/chroma:1.5.2'
    ports:
      - "8000:8000"
    volumes:
      - ../chroma_db:/data
volumes:
  db_postgres: { }
