package com.wornux;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

import org.junit.jupiter.api.Test;

class SessionSchemaMigrationTest {

    @Test
    void baselineContainsOfficialSessionSchemaAndNoCustomSnapshotTable() throws IOException {
        try (var migration = getClass().getResourceAsStream("/db/migration/V1__baseline.sql")) {
            assertThat(migration).isNotNull();
            var sql = new String(migration.readAllBytes(), StandardCharsets.UTF_8);

            assertThat(sql).contains("CREATE TABLE IF NOT EXISTS AI_SESSION (")
                    .contains("CREATE TABLE IF NOT EXISTS AI_SESSION_EVENT (")
                    .contains("seq             BIGINT        GENERATED BY DEFAULT AS IDENTITY")
                    .contains("archived        BOOLEAN       NOT NULL DEFAULT FALSE")
                    .doesNotContain("create table conversation_snapshot")
                    .doesNotContain("current_snapshot_id");
        }
    }
}
