create extension if not exists vector;
create extension if not exists pgcrypto;

-- ── Accounts & Tenants ──

create table account (
    id uuid primary key default gen_random_uuid(),
    last_tenant_account_id uuid null,
    last_group_class_member_id uuid null,
    first_name text null,
    last_name text null,
    email text not null,
    password_hash text not null,
    locked boolean not null default false,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_account_email unique (email)
);

create table tenant (
    id uuid primary key default gen_random_uuid(),
    created_by_account_id uuid null references account(id) on delete set null,
    name text not null,
    locked boolean not null default false,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table tenant_account (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    account_id uuid not null references account(id) on delete cascade,
    locked boolean not null default false,
    joined_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_tenant_account_tenant_account unique (tenant_id, account_id)
);

-- ── RBAC (internal, BIGINT identity) ──

create table role (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    description text not null,
    assignable boolean not null default true,
    priority integer not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_role_code unique (code)
);

create table resource (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_resource_code unique (code)
);

create table action (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_action_code unique (code)
);

create table permission (
    id bigint generated by default as identity primary key,
    resource_id bigint not null references resource(id) on delete cascade,
    action_id bigint not null references action(id) on delete cascade,
    code text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_permission_code unique (code),
    constraint uk_permission_resource_action unique (resource_id, action_id)
);

create table role_permission (
    role_id bigint not null references role(id) on delete cascade,
    permission_id bigint not null references permission(id) on delete cascade,
    granted_at timestamptz not null default current_timestamp,
    primary key (role_id, permission_id)
);

create table account_role (
    account_id uuid not null references account(id) on delete cascade,
    role_id bigint not null references role(id) on delete cascade,
    assigned_by_account_id uuid null references account(id) on delete set null,
    assigned_at timestamptz not null default current_timestamp,
    primary key (account_id, role_id)
);

create table tenant_account_role (
    tenant_account_id uuid not null references tenant_account(id) on delete cascade,
    role_id bigint not null references role(id) on delete cascade,
    assigned_by_tenant_account_id uuid null references tenant_account(id) on delete set null,
    assigned_at timestamptz not null default current_timestamp,
    primary key (tenant_account_id, role_id)
);

-- ── Academic structure (UUID PK) ──

create table subject (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    code text not null,
    name text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_subject_tenant_code unique (tenant_id, code)
);

create table academic_period (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    code text not null,
    name text not null,
    starts_at date not null,
    ends_at date not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_academic_period_tenant_code unique (tenant_id, code)
);

create table group_class (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    subject_id uuid not null references subject(id) on delete restrict,
    academic_period_id uuid not null references academic_period(id) on delete restrict,
    created_by_tenant_account_id uuid not null references tenant_account(id) on delete restrict,
    code text not null,
    name text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_group_class_tenant_code unique (tenant_id, code)
);

create table group_class_member (
    id uuid primary key default gen_random_uuid(),
    group_class_id uuid not null references group_class(id) on delete cascade,
    tenant_account_id uuid not null references tenant_account(id) on delete cascade,
    role text not null,
    locked boolean not null default false,
    joined_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_group_class_member_role check (role in ('PROFESSOR', 'STUDENT')),
    constraint uk_group_class_member_group_tenant_role unique (group_class_id, tenant_account_id, role)
);

create table group_class_join_code (
    id bigint generated by default as identity primary key,
    group_class_id uuid not null references group_class(id) on delete cascade,
    created_by_group_class_member_id uuid not null references group_class_member(id) on delete restrict,
    code text not null,
    active boolean not null default true,
    expires_at timestamptz null,
    max_uses integer null,
    used_count integer not null default 0,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_group_class_join_code_code unique (code)
);

-- ── Conversations (UUID for URL exposure) ──

create table conversation (
    id uuid primary key default gen_random_uuid(),
    group_class_member_id uuid not null references group_class_member(id) on delete cascade,
    title text not null,
    last_prompt_tokens integer null,
    version bigint not null default 0,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

-- Spring AI Session JDBC PostgreSQL schema copied verbatim from:
-- https://raw.githubusercontent.com/spring-ai-community/spring-ai-session/refs/heads/main/
-- spring-ai-session-jdbc/src/main/resources/org/springframework/ai/session/jdbc/schema-postgresql.sql

CREATE TABLE IF NOT EXISTS AI_SESSION (
    id            VARCHAR(255)  NOT NULL PRIMARY KEY,
    user_id       VARCHAR(255)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    expires_at    TIMESTAMP,
    metadata      TEXT,
    event_version BIGINT        NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_ai_session_user_id
    ON AI_SESSION (user_id);

CREATE INDEX IF NOT EXISTS idx_ai_session_expires_at
    ON AI_SESSION (expires_at);

CREATE TABLE IF NOT EXISTS AI_SESSION_EVENT (
    seq             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    id              VARCHAR(255)  NOT NULL PRIMARY KEY,
    session_id      VARCHAR(255)  NOT NULL,
    "timestamp"     TIMESTAMP     NOT NULL,
    message_type    VARCHAR(20)   NOT NULL,
    message_content TEXT,
    message_data    TEXT,
    synthetic       BOOLEAN       NOT NULL DEFAULT FALSE,
    archived        BOOLEAN       NOT NULL DEFAULT FALSE,
    branch          VARCHAR(500),
    metadata        TEXT,
    CONSTRAINT fk_ai_session_event_session
        FOREIGN KEY (session_id) REFERENCES AI_SESSION (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ai_session_event_session_seq
    ON AI_SESSION_EVENT (session_id, seq);

-- ── Grounding vectors ──

create table grounding_vector_store (
    id uuid primary key default gen_random_uuid(),
    content text not null,
    metadata json not null default '{}'::json,
    embedding vector(1024) not null
);

-- ── Training activities (UUID for URL exposure) ──

create table training_activity (
    id uuid primary key default gen_random_uuid(),
    group_class_id uuid not null references group_class(id) on delete cascade,
    created_by_group_class_member_id uuid not null references group_class_member(id) on delete restrict,
    title text not null,
    instructions text not null,
    status text not null,
    opens_at timestamptz null,
    closes_at timestamptz null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_training_activity_status check (status in ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED'))
);

create table training_activity_assignment (
    id uuid primary key default gen_random_uuid(),
    training_activity_id uuid not null references training_activity(id) on delete cascade,
    group_class_member_id uuid not null references group_class_member(id) on delete cascade,
    status text not null,
    assigned_at timestamptz not null default current_timestamp,
    started_at timestamptz null,
    submitted_at timestamptz null,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_training_activity_assignment_status check (
        status in ('ASSIGNED', 'STARTED', 'SUBMITTED', 'SKIPPED', 'EXPIRED', 'EXCUSED')
    ),
    constraint uk_training_activity_assignment_activity_member unique (training_activity_id, group_class_member_id)
);

-- ── Invitations (internal, BIGINT identity) ──

create table invitation (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references tenant(id) on delete cascade,
    group_class_id uuid null references group_class(id) on delete cascade,
    invited_email text not null,
    target_role text not null,
    token_hash text not null,
    status text not null default 'PENDING',
    delivery_error text null,
    expires_at timestamptz not null,
    accepted_at timestamptz null,
    invited_by_account_id uuid null references account(id) on delete set null,
    invited_by_tenant_account_id uuid null references tenant_account(id) on delete set null,
    invited_by_group_class_member_id uuid null references group_class_member(id) on delete set null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_invitation_target_role check (target_role in ('TENANT_ADMIN', 'PROFESSOR', 'STUDENT')),
    constraint chk_invitation_status check (status in ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', 'DELIVERY_FAILED')),
    constraint uk_invitation_token_hash unique (token_hash)
);

-- ── Circular FK resolution ──

alter table account
    add constraint fk_account_last_tenant_account
    foreign key (last_tenant_account_id) references tenant_account(id) on delete set null;

alter table account
    add constraint fk_account_last_group_class_member
    foreign key (last_group_class_member_id) references group_class_member(id) on delete set null;

-- ── Indexes ──

create index idx_tenant_account_tenant_id on tenant_account (tenant_id);
create index idx_tenant_account_account_id on tenant_account (account_id);
create index idx_account_role_account_id on account_role (account_id);
create index idx_account_role_role_id on account_role (role_id);
create index idx_tenant_account_role_tenant_account_id on tenant_account_role (tenant_account_id);
create index idx_tenant_account_role_role_id on tenant_account_role (role_id);
create index idx_subject_tenant_id on subject (tenant_id);
create index idx_academic_period_tenant_id on academic_period (tenant_id);
create index idx_group_class_tenant_id on group_class (tenant_id);
create index idx_group_class_subject_id on group_class (subject_id);
create index idx_group_class_academic_period_id on group_class (academic_period_id);
create index idx_group_class_member_group_class_id on group_class_member (group_class_id);
create index idx_group_class_member_tenant_account_id on group_class_member (tenant_account_id);
create index idx_group_class_join_code_group_class_id on group_class_join_code (group_class_id);
create index idx_group_class_join_code_code on group_class_join_code (code);
create index idx_conversation_group_class_member_id on conversation (group_class_member_id);
create index idx_grounding_vector_store_embedding_hnsw
    on grounding_vector_store using hnsw (embedding vector_cosine_ops);
create index idx_grounding_vector_store_group_class_id
    on grounding_vector_store ((metadata ->> 'groupClassId'));
create index idx_grounding_vector_store_created_by_group_class_member_id
    on grounding_vector_store ((metadata ->> 'createdByGroupClassMemberId'));
create index idx_grounding_vector_store_ingestion_id
    on grounding_vector_store ((metadata ->> 'ingestionId'));
create index idx_grounding_vector_store_status
    on grounding_vector_store ((metadata ->> 'status'));
create index idx_training_activity_group_class_id on training_activity (group_class_id);
create index idx_training_activity_created_by_group_class_member_id on training_activity (created_by_group_class_member_id);
create index idx_training_activity_assignment_activity_id on training_activity_assignment (training_activity_id);
create index idx_training_activity_assignment_group_class_member_id on training_activity_assignment (group_class_member_id);
create index idx_invitation_tenant_id on invitation (tenant_id);
create index idx_invitation_group_class_id on invitation (group_class_id);
create index idx_invitation_invited_email on invitation (invited_email);
create index idx_invitation_status on invitation (status);

-- ── Seed: roles ──

insert into role (code, name, description, assignable, priority, active)
values
    ('SYSTEM_ADMIN', 'System Admin', 'Platform-level administrator with full visibility.', false, 100, true),
    ('TENANT_ADMIN', 'Tenant Admin', 'Tenant-scoped academic administrator.', true, 80, true),
    ('PROFESSOR', 'Professor', 'Professor operating inside assigned group classes.', true, 60, true),
    ('STUDENT', 'Student', 'Student operating only inside owned group-class scope.', true, 40, true);

-- ── Seed: resources ──

insert into resource (code, name, description)
values
    ('TENANT', 'Tenant', 'University or institution administration.'),
    ('SUBJECT', 'Subject', 'Tenant-scoped academic subject management.'),
    ('ACADEMIC_PERIOD', 'Academic Period', 'Tenant-scoped academic period management.'),
    ('GROUP_CLASS', 'Group Class', 'Concrete class section management.'),
    ('GROUP_CLASS_MEMBER', 'Group Class Member', 'Membership and invitation management.'),
    ('GROUP_CLASS_JOIN_CODE', 'Group Class Join Code', 'Student access-code management.'),
    ('GROUNDING', 'Grounding', 'Group-class grounding configuration.'),
    ('TRAINING_ACTIVITY', 'Training Activity', 'Group-class training activity management.'),
    ('TRAINING_ACTIVITY_ASSIGNMENT', 'Training Activity Assignment', 'Assigned training activity progress for students.'),
    ('CONVERSATION', 'Conversation', 'Tutor conversation ownership and access.');

-- ── Seed: actions ──

insert into action (code, name, description)
values
    ('VIEW', 'View', 'Read or list a resource.'),
    ('CREATE', 'Create', 'Create a resource.'),
    ('UPDATE', 'Update', 'Update a resource or transition its state.'),
    ('DELETE', 'Delete', 'Remove, archive, or logically disable a resource.'),
    ('INVITE', 'Invite', 'Invite or assign another person into the resource context.');

-- ── Seed: permissions ──

insert into permission (resource_id, action_id, code, description)
select resource.id,
       action.id,
       resource.code || ':' || action.code,
       resource.name || ' ' || lower(action.code)
from resource
join action on (resource.code, action.code) in (
    ('TENANT', 'VIEW'),
    ('TENANT', 'CREATE'),
    ('TENANT', 'UPDATE'),
    ('SUBJECT', 'VIEW'),
    ('SUBJECT', 'CREATE'),
    ('SUBJECT', 'UPDATE'),
    ('SUBJECT', 'DELETE'),
    ('ACADEMIC_PERIOD', 'VIEW'),
    ('ACADEMIC_PERIOD', 'CREATE'),
    ('ACADEMIC_PERIOD', 'UPDATE'),
    ('ACADEMIC_PERIOD', 'DELETE'),
    ('GROUP_CLASS', 'VIEW'),
    ('GROUP_CLASS', 'CREATE'),
    ('GROUP_CLASS', 'UPDATE'),
    ('GROUP_CLASS', 'DELETE'),
    ('GROUP_CLASS_MEMBER', 'VIEW'),
    ('GROUP_CLASS_MEMBER', 'CREATE'),
    ('GROUP_CLASS_MEMBER', 'UPDATE'),
    ('GROUP_CLASS_MEMBER', 'DELETE'),
    ('GROUP_CLASS_MEMBER', 'INVITE'),
    ('GROUP_CLASS_JOIN_CODE', 'VIEW'),
    ('GROUP_CLASS_JOIN_CODE', 'CREATE'),
    ('GROUP_CLASS_JOIN_CODE', 'UPDATE'),
    ('GROUP_CLASS_JOIN_CODE', 'DELETE'),
    ('GROUNDING', 'VIEW'),
    ('GROUNDING', 'CREATE'),
    ('GROUNDING', 'UPDATE'),
    ('GROUNDING', 'DELETE'),
    ('TRAINING_ACTIVITY', 'VIEW'),
    ('TRAINING_ACTIVITY', 'CREATE'),
    ('TRAINING_ACTIVITY', 'UPDATE'),
    ('TRAINING_ACTIVITY', 'DELETE'),
    ('TRAINING_ACTIVITY_ASSIGNMENT', 'VIEW'),
    ('TRAINING_ACTIVITY_ASSIGNMENT', 'CREATE'),
    ('TRAINING_ACTIVITY_ASSIGNMENT', 'UPDATE'),
    ('TRAINING_ACTIVITY_ASSIGNMENT', 'DELETE'),
    ('CONVERSATION', 'VIEW'),
    ('CONVERSATION', 'CREATE'),
    ('CONVERSATION', 'UPDATE'),
    ('CONVERSATION', 'DELETE')
);

-- ── Seed: role-permission assignments ──

insert into role_permission (role_id, permission_id)
select role.id, permission.id
from role
join permission on (role.code, permission.code) in (
    ('SYSTEM_ADMIN', 'TENANT:VIEW'),
    ('SYSTEM_ADMIN', 'TENANT:CREATE'),
    ('SYSTEM_ADMIN', 'TENANT:UPDATE'),
    ('SYSTEM_ADMIN', 'SUBJECT:VIEW'),
    ('SYSTEM_ADMIN', 'ACADEMIC_PERIOD:VIEW'),
    ('SYSTEM_ADMIN', 'GROUP_CLASS:VIEW'),
    ('SYSTEM_ADMIN', 'GROUP_CLASS_MEMBER:VIEW'),
    ('SYSTEM_ADMIN', 'GROUP_CLASS_JOIN_CODE:VIEW'),
    ('SYSTEM_ADMIN', 'GROUNDING:VIEW'),
    ('SYSTEM_ADMIN', 'TRAINING_ACTIVITY:VIEW'),
    ('SYSTEM_ADMIN', 'TRAINING_ACTIVITY_ASSIGNMENT:VIEW'),
    ('SYSTEM_ADMIN', 'CONVERSATION:VIEW'),
    ('TENANT_ADMIN', 'SUBJECT:VIEW'),
    ('TENANT_ADMIN', 'SUBJECT:CREATE'),
    ('TENANT_ADMIN', 'SUBJECT:UPDATE'),
    ('TENANT_ADMIN', 'SUBJECT:DELETE'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:VIEW'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:CREATE'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:UPDATE'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:DELETE'),
    ('TENANT_ADMIN', 'GROUP_CLASS:VIEW'),
    ('TENANT_ADMIN', 'GROUP_CLASS:CREATE'),
    ('TENANT_ADMIN', 'GROUP_CLASS:UPDATE'),
    ('TENANT_ADMIN', 'GROUP_CLASS:DELETE'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:VIEW'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:INVITE'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:UPDATE'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:DELETE'),
    ('PROFESSOR', 'GROUP_CLASS:VIEW'),
    ('PROFESSOR', 'GROUP_CLASS:UPDATE'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:VIEW'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:INVITE'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:UPDATE'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:DELETE'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:VIEW'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:CREATE'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:UPDATE'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:DELETE'),
    ('PROFESSOR', 'GROUNDING:VIEW'),
    ('PROFESSOR', 'GROUNDING:CREATE'),
    ('PROFESSOR', 'GROUNDING:UPDATE'),
    ('PROFESSOR', 'GROUNDING:DELETE'),
    ('PROFESSOR', 'TRAINING_ACTIVITY:VIEW'),
    ('PROFESSOR', 'TRAINING_ACTIVITY:CREATE'),
    ('PROFESSOR', 'TRAINING_ACTIVITY:UPDATE'),
    ('PROFESSOR', 'TRAINING_ACTIVITY:DELETE'),
    ('PROFESSOR', 'TRAINING_ACTIVITY_ASSIGNMENT:VIEW'),
    ('PROFESSOR', 'TRAINING_ACTIVITY_ASSIGNMENT:CREATE'),
    ('PROFESSOR', 'TRAINING_ACTIVITY_ASSIGNMENT:UPDATE'),
    ('PROFESSOR', 'TRAINING_ACTIVITY_ASSIGNMENT:DELETE'),
    ('PROFESSOR', 'CONVERSATION:VIEW'),
    ('STUDENT', 'GROUP_CLASS:VIEW'),
    ('STUDENT', 'CONVERSATION:VIEW'),
    ('STUDENT', 'CONVERSATION:CREATE'),
    ('STUDENT', 'CONVERSATION:UPDATE'),
    ('STUDENT', 'CONVERSATION:DELETE'),
    ('STUDENT', 'TRAINING_ACTIVITY:VIEW'),
    ('STUDENT', 'TRAINING_ACTIVITY_ASSIGNMENT:VIEW'),
    ('STUDENT', 'TRAINING_ACTIVITY_ASSIGNMENT:UPDATE')
);

-- ── Seed: system admin account ──

insert into account (id, email, password_hash, locked)
values (
    '8ebd933e-20e2-42ef-adec-5331b67a0a54',
    'admin@wornux.com',
    coalesce(
        nullif(current_setting('app.initial_system_admin_password_hash', true), ''),
        '$2a$10$wUGCyVy0IhomdLcgCE.VleTywHS.MwF9bhOnqCxIj3ZqeVmG/RnrC'
    ),
    false
);

insert into account_role (account_id, role_id)
select account.id, role.id
from account
join role on role.code = 'SYSTEM_ADMIN'
where account.email = 'admin@wornux.com';
