logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:4321}/socratic-tutor}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
  docker:
    compose:
      lifecycle-management: none

  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        timeout: 5m
        max-retries: 1
      chat:
#        model: ${CHAT_MODEL:socratic-tutor:latest}
        model: ${CHAT_MODEL:qwen3:4b-instruct}
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        model: ${EMBEDDING_MODEL:qwen3-embedding:0.6b}
        options:
          dimensions: 1024
    vectorstore:
      pgvector:
        initialize-schema: false
        schema-name: public
        table-name: vector_store
        dimensions: 1024
        distance-type: COSINE_DISTANCE
        index-type: HNSW

app:
  chat:
    client-id-cookie-name: ${CHAT_CLIENT_ID_COOKIE_NAME:st_client_id}
    memory:
      max-messages: ${CHAT_MEMORY_MAX_MESSAGES:20}
  ai:
    guard:
      model: ${GUARD_MODEL:qwen2.5:3b-instruct}

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.wornux
  launch-browser: true
---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      lifecycle-management: start-only
