logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}

spring:
  docker:
    compose:
      lifecycle-management: none

  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        timeout: 5m
        max-retries: 1
      chat:
        model: ${CHAT_MODEL:llama3.1:latest}
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        model: ${EMBEDDING_MODEL:nomic-embed-text}
    vectorstore:
      chroma:
        initialize-schema: false
        collection-name: ${VECTOR_STORE_COLLECTION_NAME:socratic_tutor_collection}
        tenant-name: default_tenant
        database-name: default_database

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.wornux
  launch-browser: true
