create extension if not exists vector;
create extension if not exists pgcrypto;

create table account (
    id uuid primary key default gen_random_uuid(),
    last_tenant_account_id uuid null,
    last_group_class_member_id uuid null,
    first_name text null,
    last_name text null,
    email text not null,
    username text not null,
    password_hash text not null,
    system_admin boolean not null default false,
    locked boolean not null default false,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_account_email unique (email),
    constraint uk_account_username unique (username)
);

create table tenant (
    id uuid primary key default gen_random_uuid(),
    owner_tenant_account_id uuid null,
    name text not null,
    locked boolean not null default false,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_tenant_owner_tenant_account_id unique (owner_tenant_account_id)
);

create table tenant_account (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    account_id uuid not null references account(id) on delete cascade,
    locked boolean not null default false,
    joined_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_tenant_account_tenant_account unique (tenant_id, account_id)
);

create table role (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    description text not null,
    assignable boolean not null default true,
    priority integer not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_role_code unique (code)
);

create table resource (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_resource_code unique (code)
);

create table action (
    id bigint generated by default as identity primary key,
    code text not null,
    name text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_action_code unique (code)
);

create table permission (
    id bigint generated by default as identity primary key,
    resource_id bigint not null references resource(id) on delete cascade,
    action_id bigint not null references action(id) on delete cascade,
    code text not null,
    description text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_permission_code unique (code),
    constraint uk_permission_resource_action unique (resource_id, action_id)
);

create table role_permission (
    role_id bigint not null references role(id) on delete cascade,
    permission_id bigint not null references permission(id) on delete cascade,
    granted_at timestamptz not null default current_timestamp,
    primary key (role_id, permission_id)
);

create table tenant_account_role (
    tenant_account_id uuid not null references tenant_account(id) on delete cascade,
    role_id bigint not null references role(id) on delete cascade,
    assigned_by_tenant_account_id uuid null references tenant_account(id) on delete set null,
    assigned_at timestamptz not null default current_timestamp,
    primary key (tenant_account_id, role_id)
);

create table subject (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    code text not null,
    name text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_subject_tenant_code unique (tenant_id, code)
);

create table academic_period (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    code text not null,
    name text not null,
    starts_at date not null,
    ends_at date not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_academic_period_tenant_code unique (tenant_id, code)
);

create table group_class (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null references tenant(id) on delete cascade,
    subject_id uuid not null references subject(id) on delete restrict,
    academic_period_id uuid not null references academic_period(id) on delete restrict,
    created_by_tenant_account_id uuid not null references tenant_account(id) on delete restrict,
    code text not null,
    name text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_group_class_tenant_code unique (tenant_id, code)
);

create table group_class_member (
    id uuid primary key default gen_random_uuid(),
    group_class_id uuid not null references group_class(id) on delete cascade,
    tenant_account_id uuid not null references tenant_account(id) on delete cascade,
    role text not null,
    locked boolean not null default false,
    joined_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_group_class_member_role check (role in ('PROFESSOR', 'STUDENT', 'ASSISTANT')),
    constraint uk_group_class_member_group_tenant_role unique (group_class_id, tenant_account_id, role)
);

create table group_class_join_code (
    id uuid primary key default gen_random_uuid(),
    group_class_id uuid not null references group_class(id) on delete cascade,
    created_by_group_class_member_id uuid not null references group_class_member(id) on delete restrict,
    code text not null,
    active boolean not null default true,
    expires_at timestamptz null,
    max_uses integer null,
    used_count integer not null default 0,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_group_class_join_code_code unique (code)
);

create table conversation (
    id uuid primary key default gen_random_uuid(),
    group_class_member_id uuid not null references group_class_member(id) on delete cascade,
    current_snapshot_id bigint null,
    title text not null,
    version bigint not null default 0,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table conversation_snapshot (
    id bigint generated by default as identity primary key,
    conversation_id uuid not null references conversation(id) on delete cascade,
    previous_snapshot_id bigint null,
    snapshot_no bigint not null,
    carry_context jsonb not null default '{}'::jsonb,
    messages jsonb not null default '[]'::jsonb,
    message_count integer not null default 0,
    token_count integer not null default 0,
    version bigint not null default 0,
    created_at timestamptz not null default current_timestamp,
    compacted_at timestamptz null,
    constraint uk_conversation_snapshot_no unique (conversation_id, snapshot_no)
);

alter table conversation_snapshot
    add constraint fk_conversation_snapshot_previous
    foreign key (previous_snapshot_id) references conversation_snapshot(id) on delete set null;

alter table conversation
    add constraint fk_conversation_current_snapshot
    foreign key (current_snapshot_id) references conversation_snapshot(id) on delete set null;

create table grounding_collection (
    id bigint generated by default as identity primary key,
    group_class_id uuid not null references group_class(id) on delete cascade,
    created_by_group_class_member_id uuid not null references group_class_member(id) on delete restrict,
    name text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table grounding_document (
    id bigint generated by default as identity primary key,
    collection_id bigint not null references grounding_collection(id) on delete cascade,
    title text not null,
    source_type text not null,
    storage_key text null,
    status text not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_grounding_document_source_type check (source_type in ('UPLOAD', 'TEXT')),
    constraint chk_grounding_document_status check (status in ('PROCESSING', 'READY', 'FAILED', 'INACTIVE'))
);

create table grounding_chunk (
    id bigint generated by default as identity primary key,
    document_id bigint not null references grounding_document(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    embedding vector(1024) null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    constraint uk_grounding_chunk_document_chunk unique (document_id, chunk_index)
);

create table evaluation (
    id uuid primary key default gen_random_uuid(),
    group_class_id uuid not null references group_class(id) on delete cascade,
    created_by_group_class_member_id uuid not null references group_class_member(id) on delete restrict,
    title text not null,
    instructions text not null,
    status text not null,
    opens_at timestamptz null,
    closes_at timestamptz null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_evaluation_status check (status in ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED'))
);

create table evaluation_assignment (
    id uuid primary key default gen_random_uuid(),
    evaluation_id uuid not null references evaluation(id) on delete cascade,
    group_class_member_id uuid not null references group_class_member(id) on delete cascade,
    status text not null,
    assigned_at timestamptz not null default current_timestamp,
    started_at timestamptz null,
    submitted_at timestamptz null,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_evaluation_assignment_status check (
        status in ('ASSIGNED', 'STARTED', 'SUBMITTED', 'SKIPPED', 'EXPIRED', 'EXCUSED')
    ),
    constraint uk_evaluation_assignment_evaluation_member unique (evaluation_id, group_class_member_id)
);

alter table tenant
    add constraint fk_tenant_owner_tenant_account
    foreign key (owner_tenant_account_id) references tenant_account(id) on delete set null;

alter table account
    add constraint fk_account_last_tenant_account
    foreign key (last_tenant_account_id) references tenant_account(id) on delete set null;

alter table account
    add constraint fk_account_last_group_class_member
    foreign key (last_group_class_member_id) references group_class_member(id) on delete set null;

create index idx_tenant_account_tenant_id on tenant_account (tenant_id);
create index idx_tenant_account_account_id on tenant_account (account_id);
create index idx_tenant_account_role_tenant_account_id on tenant_account_role (tenant_account_id);
create index idx_tenant_account_role_role_id on tenant_account_role (role_id);
create index idx_subject_tenant_id on subject (tenant_id);
create index idx_academic_period_tenant_id on academic_period (tenant_id);
create index idx_group_class_tenant_id on group_class (tenant_id);
create index idx_group_class_subject_id on group_class (subject_id);
create index idx_group_class_academic_period_id on group_class (academic_period_id);
create index idx_group_class_member_group_class_id on group_class_member (group_class_id);
create index idx_group_class_member_tenant_account_id on group_class_member (tenant_account_id);
create index idx_group_class_join_code_group_class_id on group_class_join_code (group_class_id);
create index idx_group_class_join_code_code on group_class_join_code (code);
create index idx_conversation_group_class_member_id on conversation (group_class_member_id);
create index idx_conversation_current_snapshot_id on conversation (current_snapshot_id);
create index idx_conversation_snapshot_conversation_id on conversation_snapshot (conversation_id);
create index idx_conversation_snapshot_previous_snapshot_id on conversation_snapshot (previous_snapshot_id);
create index idx_grounding_collection_group_class_id on grounding_collection (group_class_id);
create index idx_grounding_document_collection_id on grounding_document (collection_id);
create index idx_grounding_chunk_document_id on grounding_chunk (document_id);
create index idx_evaluation_group_class_id on evaluation (group_class_id);
create index idx_evaluation_created_by_group_class_member_id on evaluation (created_by_group_class_member_id);
create index idx_evaluation_assignment_evaluation_id on evaluation_assignment (evaluation_id);
create index idx_evaluation_assignment_group_class_member_id on evaluation_assignment (group_class_member_id);

insert into role (code, name, description, assignable, priority, active)
values
    ('SYSTEM_ADMIN', 'System Admin', 'Platform-level administrator with full visibility.', false, 100, true),
    ('TENANT_ADMIN', 'Tenant Admin', 'Tenant-scoped academic administrator.', true, 80, true),
    ('PROFESSOR', 'Professor', 'Professor operating inside assigned group classes.', true, 60, true),
    ('STUDENT', 'Student', 'Student operating only inside owned group-class scope.', true, 40, true),
    ('ASSISTANT', 'Assistant', 'Assistant role reserved for later workflow use cases.', true, 50, true);

insert into resource (code, name, description)
values
    ('TENANT', 'Tenant', 'University or institution administration.'),
    ('SUBJECT', 'Subject', 'Tenant-scoped academic subject management.'),
    ('ACADEMIC_PERIOD', 'Academic Period', 'Tenant-scoped academic period management.'),
    ('GROUP_CLASS', 'Group Class', 'Concrete class section management.'),
    ('GROUP_CLASS_MEMBER', 'Group Class Member', 'Membership and invitation management.'),
    ('GROUP_CLASS_JOIN_CODE', 'Group Class Join Code', 'Student access-code management.'),
    ('GROUNDING', 'Grounding', 'Group-class grounding configuration.'),
    ('EVALUATION', 'Evaluation', 'Group-class evaluation management.'),
    ('EVALUATION_ASSIGNMENT', 'Evaluation Assignment', 'Assigned evaluation progress for students.'),
    ('CONVERSATION', 'Conversation', 'Tutor conversation ownership and access.');

insert into action (code, name, description)
values
    ('VIEW', 'View', 'Read or list a resource.'),
    ('CREATE', 'Create', 'Create a resource.'),
    ('UPDATE', 'Update', 'Update a resource or transition its state.'),
    ('DELETE', 'Delete', 'Remove, archive, or logically disable a resource.'),
    ('INVITE', 'Invite', 'Invite or assign another person into the resource context.');

insert into permission (resource_id, action_id, code, description)
select resource.id,
       action.id,
       resource.code || ':' || action.code,
       resource.name || ' ' || lower(action.code)
from resource
join action on (resource.code, action.code) in (
    ('TENANT', 'VIEW'),
    ('TENANT', 'CREATE'),
    ('TENANT', 'UPDATE'),
    ('SUBJECT', 'VIEW'),
    ('SUBJECT', 'CREATE'),
    ('SUBJECT', 'UPDATE'),
    ('SUBJECT', 'DELETE'),
    ('ACADEMIC_PERIOD', 'VIEW'),
    ('ACADEMIC_PERIOD', 'CREATE'),
    ('ACADEMIC_PERIOD', 'UPDATE'),
    ('ACADEMIC_PERIOD', 'DELETE'),
    ('GROUP_CLASS', 'VIEW'),
    ('GROUP_CLASS', 'CREATE'),
    ('GROUP_CLASS', 'UPDATE'),
    ('GROUP_CLASS', 'DELETE'),
    ('GROUP_CLASS_MEMBER', 'VIEW'),
    ('GROUP_CLASS_MEMBER', 'CREATE'),
    ('GROUP_CLASS_MEMBER', 'UPDATE'),
    ('GROUP_CLASS_MEMBER', 'DELETE'),
    ('GROUP_CLASS_MEMBER', 'INVITE'),
    ('GROUP_CLASS_JOIN_CODE', 'VIEW'),
    ('GROUP_CLASS_JOIN_CODE', 'CREATE'),
    ('GROUP_CLASS_JOIN_CODE', 'UPDATE'),
    ('GROUP_CLASS_JOIN_CODE', 'DELETE'),
    ('GROUNDING', 'VIEW'),
    ('GROUNDING', 'CREATE'),
    ('GROUNDING', 'UPDATE'),
    ('GROUNDING', 'DELETE'),
    ('EVALUATION', 'VIEW'),
    ('EVALUATION', 'CREATE'),
    ('EVALUATION', 'UPDATE'),
    ('EVALUATION', 'DELETE'),
    ('EVALUATION_ASSIGNMENT', 'VIEW'),
    ('EVALUATION_ASSIGNMENT', 'CREATE'),
    ('EVALUATION_ASSIGNMENT', 'UPDATE'),
    ('EVALUATION_ASSIGNMENT', 'DELETE'),
    ('CONVERSATION', 'VIEW'),
    ('CONVERSATION', 'CREATE'),
    ('CONVERSATION', 'UPDATE'),
    ('CONVERSATION', 'DELETE')
);

insert into role_permission (role_id, permission_id)
select role.id, permission.id
from role
join permission on (role.code, permission.code) in (
    ('SYSTEM_ADMIN', 'TENANT:VIEW'),
    ('SYSTEM_ADMIN', 'TENANT:CREATE'),
    ('SYSTEM_ADMIN', 'TENANT:UPDATE'),
    ('SYSTEM_ADMIN', 'SUBJECT:VIEW'),
    ('SYSTEM_ADMIN', 'ACADEMIC_PERIOD:VIEW'),
    ('SYSTEM_ADMIN', 'GROUP_CLASS:VIEW'),
    ('SYSTEM_ADMIN', 'GROUP_CLASS_MEMBER:VIEW'),
    ('SYSTEM_ADMIN', 'GROUP_CLASS_JOIN_CODE:VIEW'),
    ('SYSTEM_ADMIN', 'GROUNDING:VIEW'),
    ('SYSTEM_ADMIN', 'EVALUATION:VIEW'),
    ('SYSTEM_ADMIN', 'EVALUATION_ASSIGNMENT:VIEW'),
    ('SYSTEM_ADMIN', 'CONVERSATION:VIEW'),
    ('TENANT_ADMIN', 'SUBJECT:VIEW'),
    ('TENANT_ADMIN', 'SUBJECT:CREATE'),
    ('TENANT_ADMIN', 'SUBJECT:UPDATE'),
    ('TENANT_ADMIN', 'SUBJECT:DELETE'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:VIEW'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:CREATE'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:UPDATE'),
    ('TENANT_ADMIN', 'ACADEMIC_PERIOD:DELETE'),
    ('TENANT_ADMIN', 'GROUP_CLASS:VIEW'),
    ('TENANT_ADMIN', 'GROUP_CLASS:CREATE'),
    ('TENANT_ADMIN', 'GROUP_CLASS:UPDATE'),
    ('TENANT_ADMIN', 'GROUP_CLASS:DELETE'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:VIEW'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:INVITE'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:UPDATE'),
    ('TENANT_ADMIN', 'GROUP_CLASS_MEMBER:DELETE'),
    ('PROFESSOR', 'GROUP_CLASS:VIEW'),
    ('PROFESSOR', 'GROUP_CLASS:UPDATE'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:VIEW'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:INVITE'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:UPDATE'),
    ('PROFESSOR', 'GROUP_CLASS_MEMBER:DELETE'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:VIEW'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:CREATE'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:UPDATE'),
    ('PROFESSOR', 'GROUP_CLASS_JOIN_CODE:DELETE'),
    ('PROFESSOR', 'GROUNDING:VIEW'),
    ('PROFESSOR', 'GROUNDING:CREATE'),
    ('PROFESSOR', 'GROUNDING:UPDATE'),
    ('PROFESSOR', 'GROUNDING:DELETE'),
    ('PROFESSOR', 'EVALUATION:VIEW'),
    ('PROFESSOR', 'EVALUATION:CREATE'),
    ('PROFESSOR', 'EVALUATION:UPDATE'),
    ('PROFESSOR', 'EVALUATION:DELETE'),
    ('PROFESSOR', 'EVALUATION_ASSIGNMENT:VIEW'),
    ('PROFESSOR', 'EVALUATION_ASSIGNMENT:CREATE'),
    ('PROFESSOR', 'EVALUATION_ASSIGNMENT:UPDATE'),
    ('PROFESSOR', 'EVALUATION_ASSIGNMENT:DELETE'),
    ('PROFESSOR', 'CONVERSATION:VIEW'),
    ('STUDENT', 'GROUP_CLASS:VIEW'),
    ('STUDENT', 'CONVERSATION:VIEW'),
    ('STUDENT', 'CONVERSATION:CREATE'),
    ('STUDENT', 'CONVERSATION:UPDATE'),
    ('STUDENT', 'CONVERSATION:DELETE'),
    ('STUDENT', 'EVALUATION:VIEW'),
    ('STUDENT', 'EVALUATION_ASSIGNMENT:VIEW'),
    ('STUDENT', 'EVALUATION_ASSIGNMENT:UPDATE')
);

insert into account (email, username, password_hash, system_admin, locked)
values (
    'admin@socratic-tutor.com',
    'admin',
    coalesce(
        nullif(current_setting('app.initial_system_admin_password_hash', true), ''),
        crypt(gen_random_uuid()::text || gen_random_uuid()::text, gen_salt('bf', 12))
    ),
    true,
    false
);
